# Generated by Django 5.2.7 on 2025-12-02 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sabuzz', '0005_journalistrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('pending', 'Pending Approval')], default='pending', max_length=20),
        ),
    ]
